field: 6794d760-f90a-434f-a092-f85296f202b9 # Menu Specials Neo
fieldLayouts:
  e146776a-0a39-45fc-b0bf-4c6f33c8039a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d42406ca-00a3-4bb9-b8e6-3d76a3bf1a90 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47f05900-9068-49b9-bdef-1f1f51146184
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d06a8e51-7658-433d-b57e-3e458cde407a # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 558d6981-8165-443b-aed2-7a8fc707a00e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 794abc79-8935-426e-9d21-37e74fd19d0a # Special Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55a63f07-61a2-4ed9-8425-1c6aecd1d560
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ba42ba0-6bce-4b06-ab10-7c338e2cf9c8
        userCondition: null
fields:
  794abc79-8935-426e-9d21-37e74fd19d0a: # Special Price
    columnSuffix: yoxombju
    contentColumnType: text
    fieldGroup: null
    handle: specialPrice
    instructions: null
    name: 'Special Price'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d06a8e51-7658-433d-b57e-3e458cde407a: # Description
    columnSuffix: qyxgyric
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d42406ca-00a3-4bb9-b8e6-3d76a3bf1a90: # Headline
    columnSuffix: qayemlxp
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: specialBespokeItem
name: 'Special Bespoke Item'
sortOrder: 2
