fieldLayouts:
  9e5ade6d-9ee1-4e8a-9a95-491495fd6da5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a4da895-2155-4ff1-a99a-2b0aa95886a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e73d7696-f650-4b27-94da-44d77d35b8ed # Body Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e8d1dbc-5a31-44c9-9cf4-a389e960782a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2df6738d-ff88-456e-849d-8c1468bdf4fc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 291cce60-cee5-4519-ac13-6b4c185778be # Where this is used
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7c41a12-fc1c-4f73-9518-e7ea107254ec
            userCondition: null
            warning: null
            width: 100
        name: Usage
        uid: 1e1f2f69-afd7-45e0-88da-08ed45cf22a5
        userCondition: null
handle: components
hasTitleField: true
name: Components
section: be6c5c79-5a2f-4df0-8b79-a4f6b7cdb0e3 # Body Texts
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
