fieldLayouts:
  8dee91ae-850c-450d-84bc-071c773b08c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e0383cf-59de-4941-b77f-29776990528c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc1034c7-85f2-41f9-a6ef-4178711c9165 # Page Components
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 188c819c-1c97-429c-980c-351b4c0afbec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 497e17ed-f170-44d7-ae5c-5c64a90749f6
        userCondition: null
handle: entry
hasTitleField: true
name: Entry
section: 81cd123f-fa9e-4fbc-bc0a-06d4cd3b69af # Entry
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
