fieldLayouts:
  b08dd0fe-a6db-4a69-8dab-e3ba373dba7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a5096f8e-1735-45c9-9b6c-d4ca246bb7c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc1034c7-85f2-41f9-a6ef-4178711c9165 # Page Components
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ee2aaf1-628b-4c21-a7aa-e2ef1db621e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09156442-21ed-4915-a1b8-45cd32d3fded
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 02ff2eb7-51b8-432e-a52e-12f5b3fbf090 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
