fieldLayouts:
  e08c2fa3-8e2d-4042-96b3-d72112d3a0e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ee3ea1c9-b07d-4829-bc7e-2728b6cacb29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 131b4628-df79-47f8-ba09-b3ef213112be # Menu Specials Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd2c3cba-75ac-46f5-91b7-b2849e11013b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7dc8da14-4bae-40f6-b4a4-4b2b768fd543
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 291cce60-cee5-4519-ac13-6b4c185778be # Where this is used
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecc8c135-1da8-42b0-95bc-3d4d1ef74894
            userCondition: null
            warning: null
            width: 100
        name: Usage
        uid: 38088730-079c-448b-ae0d-c407bce37ded
        userCondition: null
handle: menuSpecialsComponent
hasTitleField: true
name: 'Menu Specials Component'
section: ce0a2281-7787-4a34-9930-702ed9f183a1 # Menus
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
