fieldLayouts:
  94b2dbb8-2af1-4275-9db7-bf69a106a3a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 553cdfdd-864f-4bb3-8df3-fa7e33761c2c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 13024e93-d6bc-4672-bc18-11dd61f8ba1d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 291cce60-cee5-4519-ac13-6b4c185778be # Where this is used
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82f4ff87-8c7e-4bf8-ac27-858550782a9a
            userCondition: null
            warning: null
            width: 100
        name: Usage
        uid: f02c80f7-af8b-44cf-b372-6b4990489bf9
        userCondition: null
handle: menuItemComponent
hasTitleField: true
name: 'Menu Item Component'
section: ce0a2281-7787-4a34-9930-702ed9f183a1 # Menus
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
