childBlocks: null
description: ''
enabled: true
field: b42b8396-352b-4052-b2cb-49107b48cca1 # Component Builder (Neo)
fieldLayouts:
  894f7bc1-ce7e-4cfb-9149-448ce3801215:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d1be453b-16b3-4a32-a058-d2518e7679c5 # Hero Slides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa85af39-ff3d-4e30-b3b5-01b32a4a1422
            userCondition: null
            warning: null
            width: 100
        name: Slides
        uid: eb460b45-a6d9-4e2e-97b3-bcf5a6b9d7b2
        userCondition: null
group: null
handle: hero
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Hero
sortOrder: 1
topLevel: true
