childBlocks: null
description: ''
enabled: true
field: b42b8396-352b-4052-b2cb-49107b48cca1 # Component Builder (Neo)
fieldLayouts:
  8ce10274-be5a-4a76-a989-68a563d61124:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6794d760-f90a-434f-a092-f85296f202b9 # Menu Specials Neo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cad74496-806e-4ecd-b5d7-51bb96438991
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 222b2cc7-23ec-4bcd-b682-799ca18a2722
        userCondition: null
group: null
handle: menuSpecials
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Menu Specials'
sortOrder: 3
topLevel: true
