childBlocks: null
description: ''
enabled: true
field: b42b8396-352b-4052-b2cb-49107b48cca1 # Component Builder (Neo)
fieldLayouts:
  7e973ecf-0b06-4480-8196-7546419ab541:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 86db7437-2889-46f1-99d0-ff35bc94f5b7 # Menu Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f17692fa-0aac-49ea-bd55-9a817e3b66d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3661daaf-6f05-43e9-b9f0-67e2b60bfd49
        userCondition: null
group: null
handle: menuCollection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Menu Collection'
sortOrder: 5
topLevel: true
