fieldLayouts:
  d8f72abc-af12-4179-9acc-f1b7c3f2f854:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6c9be3a8-954a-450e-a14e-068702f990fe
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 51a24001-c05d-4dbb-aa27-b7caf8f43ffb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03900fa8-5354-4ac5-8544-e1314fa6daf0
        userCondition: null
fs: heroImages
handle: heroImages
name: 'Hero Images'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
