columnSuffix: kyttlbbd
contentColumnType: text
fieldGroup: 6af778c6-d1f3-48bb-954a-b7b078d1a144 # Menu Category
handle: menuBody
instructions: null
name: 'Menu Body'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
