columnSuffix: null
contentColumnType: string
fieldGroup: 2509fa8e-d195-4240-90f5-eb16a4b66cc5 # Menu Component
handle: menuSpecialsItems
instructions: null
name: 'Menu Specials Items'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
