defaultPlacement: end
enableVersioning: true
handle: bodyTexts
name: 'Body Texts'
propagationMethod: all
siteSettings:
  1c804e03-e137-4bc5-9494-da5b7010d255: # Holts Dogs
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: faff6c89-0738-40b2-b54e-5ed0fc3cb773
type: structure
