defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  1c804e03-e137-4bc5-9494-da5b7010d255: # Holts Dogs
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
