defaultPlacement: end
enableVersioning: true
handle: menus
name: Menus
propagationMethod: all
siteSettings:
  1c804e03-e137-4bc5-9494-da5b7010d255: # Holts Dogs
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 8b759850-a3f1-479d-9053-8d37797010b0
type: structure
